AWSTemplateFormatVersion: "2010-09-09"
Description: "An example template with an IAM role for a sample state machine : parallel"
Parameters:
  GlueS3Bucket:
    Type: String
    Default: aws-glue-scripts-m3d1pb
    Description: "Enter S3 bucket name for Glue scripts"
  GlueJobName:
    Type: String
    Default: sm-parallel2-gluejob

Resources:
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "states:DescribeStateMachine"
                  - "states:StartExecution"
                  - "states:DeleteStateMachine"
                  - "states:ListExecutions"
                  - "states:UpdateStateMachine"
                  - "events:PutTargets"
                  - "events:PutRule"
                  - "events:DescribeRule"
                  - "glue:*"
                  - "lambda:InvokeFunction"
                  - "s3:ListAllMyBuckets"
                Resource: "*"
  StateMachineParent:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: sm-parallel2-Parent
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Example to invoke AWS Glue Job",
              "StartAt": "Preprocessing",
              "States": {
                "Preprocessing": {
                  "Type": "Task",
                  "Resource": "${LambdaFunctionArn}",
                  "ResultPath": "$.BucketList",
                  "Next": "ExecuteParallelJobs"
                },
                "ExecuteParallelJobs": {
                  "Type": "Map",
                  "InputPath": "$.BucketList",
                  "MaxConcurrency": 5,
                  "Next": "Finished",
                  "Iterator":
                    {
                      "StartAt": "job",
                      "States": {
                        "job": {
                          "Type": "Task",
                          "Resource": "arn:aws:states:::states:startExecution.sync",
                          "InputPath": "$",
                          "Parameters": {
                            "StateMachineArn": "${StateMachine1}",
                            "Input": {
                              "BucketName.$": "$"
                            }
                          },
                          "End": true
                        }
                      }
                  },
                  "Catch": [
                    {
                      "ErrorEquals": ["States.TaskFailed"],
                      "Next": "NotifyFailure",
                      "ResultPath": "$.cause"
                    }
                  ]
                },
                "Finished": {
                  "Type": "Succeed"
                },
                "NotifyFailure": {
                  "Comment": "Write here failure notification",
                  "Type": "Pass",
                  "Next": "ExecutionFailed"
                },
                "ExecutionFailed": {
                  "Type": "Fail",
                  "Cause": "Glue Job failed"
                }
              }
            }
          - {StateMachine1: !Ref StateMachineChild,
            LambdaFunctionArn: !GetAtt [LambdaListBucket, Arn]}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
  StateMachineChild:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      StateMachineName: sm-parallel2-job
      DefinitionString:
        !Sub 
          - |-
            {
              "Comment": "Example to execute AWS Glue Job",
              "StartAt": "Prep",
              "States": {
                "Prep": {
                  "Comment": "Write prep if you need",
                  "Type": "Pass",
                  "Next": "ExecuteGlueJob"
                },
                "ExecuteGlueJob": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::glue:startJobRun.sync",
                  "Parameters": {
                    "JobName": "${GlueJobName}",
                    "Arguments": {
                      "--bucket_name.$": "$.BucketName"
                    }
                  },
                  "Next": "Finished",
                  "Catch": [
                    {
                      "ErrorEquals": ["States.TaskFailed"],
                      "Next": "NotifyFailure",
                      "ResultPath": "$.cause"
                    }
                  ]
                },
                "Finished": {
                  "Type": "Succeed"
                },
                "NotifyFailure": {
                  "Comment": "ジョブの失敗通知を記述",
                  "Type": "Pass",
                  "Next": "ExecutionFailed"
                },
                "ExecutionFailed": {
                  "Type": "Fail",
                  "Cause" : "$.cause"
                }
              }
            }
          - {GlueJobName: !Ref GlueJobName}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "GlueJobExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "glue:*"
                  - "s3:GetBucketLocation"
                  - "s3:ListBucket"
                  - "s3:ListAllMyBuckets"
                  - "s3:GetBucketAcl"
                  - "ec2:DescribeVpcEndpoints"
                  - "ec2:DescribeRouteTables"
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DeleteNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcAttribute"
                  - "iam:ListRolePolicies"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "cloudwatch:PutMetricData"                
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "s3:CreateBucket"
                Resource: "arn:aws:s3:::aws-glue-*"
              - Effect: "Allow"
                Action:
                  - "s3:CreateBucket"
                Resource: "arn:aws:s3:::aws-glue-*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource: 
                  - "arn:aws:s3:::aws-glue-*/*"
                  - "arn:aws:s3:::*/*aws-glue-*/*"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource: 
                  - "arn:aws:s3:::crawler-public*"
                  - "arn:aws:s3:::aws-glue-*"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:AssociateKmsKey"                
                Resource: 
                  - "arn:aws:logs:*:*:/aws-glue/*"
              - Effect: "Allow"
                Action:
                  - "ec2:CreateTags"
                  - "ec2:DeleteTags"
                Condition:
                  ForAllValues:StringEquals:
                    aws:TagKeys:
                      - "aws-glue-service-resource"
                Resource: 
                  - "arn:aws:ec2:*:*:network-interface/*"
                  - "arn:aws:ec2:*:*:security-group/*"
                  - "arn:aws:ec2:*:*:instance/*"
  GlueJob1:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: 
          !Join [ '', ['s3://', !Ref GlueS3Bucket, '/scripts/glue_job4.py']]
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
      ExecutionProperty:
        MaxConcurrentRuns: 8
      GlueVersion: 1.0
      MaxRetries: 0
      MaxCapacity: 0.0625
      Name: !Ref GlueJobName
      Role: !Ref GlueJobRole

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub lambda.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                  - "s3:ListAllMyBuckets"
                Resource: "*"
  LambdaListBucket:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: index.list_bucket
      FunctionName: list_bucket
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Code:
        ZipFile: |
          import boto3

          def list_bucket(event, context):
            s3_client = boto3.client('s3')

            list_buckets_response = s3_client.list_buckets()
            buckets = [x['Name'] for x in list_buckets_response['Buckets']]

            return buckets